In [1]:
import numpy as np
from Client import Clients

In [2]:
category_dict = {}
category_dict["Informatique"] = ["Tablette", "Ordinateur", "Portable"]
category_dict["Film"] = ["DVD", "TV", "Cinéma"]

In [3]:
# def count(y):
#     return sum([len(y.get(x, 0)) for x in y])

In [4]:
# class Client:
#     def __init__(self, n_client, category_dict):
#         self.category_dict = category_dict
#         self.n_client = n_client
#         self.n_category = len(category_dict.keys())
#         self.n_commodity = count(category_dict)
#         self.preference_matrix = np.zeros((n_client, self.n_commodity))
        
#     def generate_client_distribution():
#         np.random.uniform(0, 0.8, (n_client, self.n_category)) + 

In [5]:
C = Clients(n_client=10, category_dict=category_dict)

In [6]:
print(C.proba_commodity)

[[0.87582018 0.82167852 0.85616648 0.18628541 0.24837628 0.25507377]
 [0.43796762 0.39778533 0.44743938 0.40563434 0.36802372 0.41824772]
 [0.74435053 0.75785016 0.81834957 0.5557154  0.56070046 0.56899275]
 [0.11470947 0.11276636 0.09462537 0.79135219 0.8065881  0.86343222]
 [0.55980421 0.51121649 0.5171639  0.87315152 0.93411681 0.93216036]
 [0.08398602 0.06268527 0.06802918 0.93344043 0.93876124 0.8868556 ]
 [0.83596329 0.76554247 0.82493553 0.31882235 0.40573351 0.3432796 ]
 [0.90253139 0.86878381 0.81869009 0.52198014 0.49820257 0.47022956]
 [0.1591542  0.14240138 0.19219568 0.82857368 0.78685985 0.79334344]
 [0.56526136 0.57228144 0.55003298 0.5051399  0.54458338 0.46807311]]


In [7]:
print(C.category_list[0])

Informatique


In [2]:
class AgentBase():
    def __init__(self, commodity_number, recommendation_length):
        raise NotImplementedError()
    
    def recommend(self, online_client):
        raise NotImplementedError()
    
    def update_state(self, recommendation_chosen, reward):
        raise NotImplementedError()
        
    def get_agent_name(self):
        raise NotImplementedError()

In [ ]:
class RandomAgent(AgentBase):
    def __init__(self, commodity_number, recommendation_length=5):
        self.name = 'random agent'
        self.commodity_number = commodity_number
        self.recommendation_length = recommendation_length
        
    def recommend(self, online_client):
        return np.random.randint(0, commodity_number)
    
    def update_state(self, recommendation_chosen, reward):
        pass
    
    def get_agent_name(self):
        return self.name